[features]
seeds = false
skip-lint = false
[programs.localnet]
treasure_hunt = "FR1jX3PWkGr1bsePg9td9e2mc9neEPbjcaABomdWM3ZR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/joe/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
